--[[
	Events:
		ACTIONBAR_HIDEGRID
		ACTIONBAR_PAGE_CHANGED
		ACTIONBAR_SHOWGRID
		ACTIONBAR_SLOT_CHANGED
		ACTIONBAR_UPDATE_COOLDOWN
		ACTIONBAR_UPDATE_STATE
		ACTIONBAR_UPDATE_USABLE
		
		ACTIVE_TALENT_GROUP_CHANGED
		
		ADDON_ACTION_BLOCKED
		ADDON_ACTION_FORBIDDEN
		ADDON_LOADED
		
		AREA_SPIRIT_HEALER_IN_RANGE
		AREA_SPIRIT_HEALER_OUT_OF_RANGE
		
		ARENA_TEAM_INVITE_REQUEST
		ARENA_TEAM_ROSTER_UPDATE
		ARENA_TEAM_UPDATE
		ARENA_OPPONENT_UPDATE
		ARENA_SEASON_WORLD_STATE
		
		AUCTION_BIDDER_LIST_UPDATE
		AUCTION_HOUSE_CLOSED
		AUCTION_HOUSE_DISABLED
		AUCTION_HOUSE_SHOW
		AUCTION_ITEM_LIST_UPDATE
		AUCTION_MULTISELL_FAILURE
		AUCTION_MULTISELL_START
		AUCTION_MULTISELL_UPDATE
		AUCTION_OWNED_LIST_UPDATE
		
		AUTOEQUIP_BIND_CONFIRM
		AUTOFOLLOW_BEGIN
		AUTOFOLLOW_END
]]--

local Engine = getglobal('ElronsUI')