--[[
	Events:
		BAG_CLOSED
		BAG_OPEN
		BAG_UPDATE
		BAG_UPDATE_COOLDOWN
		
		BANKFRAME_CLOSED
		BANKFRAME_OPENED
		
		BATTLEFIELDS_CLOSED
		BATTLEFIELDS_SHOW
		BATTLEFIELD_MGR_EJECTED
		BATTLEFIELD_MGR_EJECT_PENDING
		BATTLEFIELD_MGR_ENTERED
		BATTLEFIELD_MGR_ENTRY_INVITE
		BATTLEFIELD_MGR_QUEUE_INVITE
		BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE
		BATTLEFIELD_MGR_STATE_CHANGE
		
		BILLING_NAG_DIALOG
		
		BIND_ENCHANT
]]--

local Engine = getglobal('ElronsUI')