--[[
	Events:
		CANCEL_LOOT_ROLL
		CANCEL_SUMMON
		
		CHANNEL_COUNT_UPDATE
		CHANNEL_FLAGS_UPDATED
		CHANNEL_INVITE_REQUEST
		CHANNEL_PASSWORD_REQUEST
		CHANNEL_ROSTER_UPDATE
		CHANNEL_UI_UPDATE
		CHANNEL_VOICE_UPDATE
		CHARACTER_POINTS_CHANGED
		CHAT_MSG_ACHIEVEMENT
]]--

local Engine = getglobal('ElronsUI')